# Generated by Django 5.0.6 on 2024-07-08 04:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('idMachine', models.AutoField(primary_key=True, serialize=False)),
                ('machineName', models.CharField(max_length=100)),
                ('assignedUser', models.CharField(blank=True, max_length=100, null=True)),
                ('machineStatus', models.CharField(max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operatingSystem', models.CharField(max_length=50)),
                ('installedSoftware', models.TextField()),
                ('lastMaintenance', models.DateField()),
                ('acquisitionDate', models.DateField()),
                ('ipAddress', models.CharField(max_length=15)),
                ('macAddress', models.CharField(max_length=17)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('hardDrive', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfProduct', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueDate', models.DateField()),
                ('kindOfProduct', models.CharField(choices=[('B', 'Bebidas'), ('S', 'Snacks'), ('F', 'Frutas'), ('P', 'Peluches'), ('G', 'Golosinas'), ('O', 'Otro')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifRange', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('client', 'Client')], default='client', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('lastName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservationStatus', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('idMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberManage.machine')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberManage.product')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberManage.user')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machineRange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberManage.tariff'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('transactionStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('idMachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberManage.machine')),
                ('idProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberManage.product')),
                ('idReservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CyberManage.reservation')),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberManage.user')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creditCardBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirationDate', models.DateField()),
                ('creditCardNumber', models.CharField(max_length=16)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='CyberManage.user')),
            ],
        ),
    ]
