# Generated by Django 5.0.7 on 2024-07-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberManage', '0002_remove_machine_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='idProduct',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='idProduct',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Employee'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
