# Generated by Django 5.0.7 on 2024-07-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberManage', '0004_events_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
