# Generated by Django 5.0.7 on 2024-07-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberManage', '0005_rename_events_event_rename_promotions_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='nameEvent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineStatus',
            field=models.CharField(choices=[('available', 'Disponible'), ('booked', 'Reservada'), ('disabled', 'Deshabilitada')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Employee'), ('client', 'Client')], default='client', max_length=15),
        ),
    ]
